### ISSUE TITLE
python<=2.6 compatibility is broken by latest commit in master

### ISSUE THREAD

**Issue by mvk** [isislovecruft/python-gnupg#104]
hi.
master branch breaks py2 compatiblity using `sys.version_info.major` to check it is indeed py2.
on py2 this is just a tuple. on py3 this is an object with attributes, one of which is referred to by line 55 in file `_utils.py`.
My patch simply replaces the code with py2 safe code.
I looked at "six" module in hope to find some kind of twofold compatibility, i.e. to write in py3 syntax, yet to still be compatible with py2... well it seems with sys there's a problem there.

**Comment by isislovecruft** [comment]
@mvk Yikes, you're totally right! Though [this only affects Python <= 2.6](https://docs.python.org/2/library/sys.html#sys.version_info), not Python2.7. Thanks for finding this.

**Comment by isislovecruft** [comment]
Ignore the above commit — I typed #104, when I meant to type #102, in that commit message.

**Comment by mvk** [comment]
Hi, no problem.
When is this going to be in pypi?
