### ISSUE TITLE
Inconsistent behaviour for gnupghome

### ISSUE THREAD

**Issue by slafs** [isislovecruft/python-gnupg#107]
When instantiating GPG class from some directory, say ``/tmp`` (other than HOME dir), like this

    gpg = gnupg.GPG(gnupghome='~/.gnupg')

those two directories are created inside ``/tmp`` dir, like so:

    /tmp/~/.gnupg

but if I use that ``gpg`` object (e.g. ``gpg.decrypt(text)``), then the path for homedir gets expanded and the library uses my gnupg home directory (i.e. ``$HOME/.gnupg``).

Documentation says that ``gnupghome`` shouldn't contain any special characters but I guess ``~`` could be expanded while instantiating the class as a special case scenario (I also assume treating ``~`` as a regular character, while working with the library, can't be done easily).

**Comment by kerstin** [comment]
I'm not exactly sure what your issue is about – are you asking for the tilde to get auto-expanded to the user's home directory when using gnupg (instead of having to do it manually as is the case with Python code in general)?

**Comment by kerstin** [comment]
Also, seeing as you used ```gnupghome``` to refer to the home directory: did you simply get it mixed up with ```homedir``` or did you confuse the two libraries?

This one's called ```python-gnupg``` here on GitHub but the package name is actually ```gnupg``` and it's based on the original ```python-gnupg``` package (which I think is also still being developed, and which would get installed as ```python-gnupg```).

**Comment by slafs** [comment]
> Also, seeing as you used gnupghome to refer to the home directory: did you simply get it mixed up with homedir or did you confuse the two libraries?

Apparently I didn't know there are two different libraries and I did mean `python-gnupg`. Also my issue desc is terrible. Even I have problems understanding myself. 
Sorry for the noise.

**Comment by kerstin** [comment]
@slafs I'm a fellow user who's had the same happen to them. ^^ And we're not alone, there are actually a couple of issues with the same topic.

I think the most confusing parts are that library name and repo name don't match up and that the latter is identical with the other library's name, and that both libraries are imported using `gnupg`.

**Comment by kerstin** [comment]
PS: I was originally interested in your question because I misunderstood the usage of homedir/gnuhome in both libraries (see #146).

I'm also using the original `python-gnupg` now though because I unfortunately can't get `gnupg` to work on Linux... (#145)
