### ISSUE TITLE
Issue on some linux installations

### ISSUE THREAD

**Issue by marcwebbie** [isislovecruft/python-gnupg#109]
Hello, 

I've been experiencing a lot of issues on some linux boxes with encoding. This happens only on `python2`:

``` bash
  File "/usr/local/lib/python2.7/dist-packages/gnupg/gnupg.py", line 972, in encrypt
    stream = _make_binary_stream(data, self._encoding)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_util.py", line 547, in _make_binary_stream
    thing = thing.encode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
```

Any idea on where should I start looking at?

**Comment by isislovecruft** [comment]
@marcwebbie Hi! Thanks for reporting this. May I ask which version you're using? Did it only start happening with that version, or do you know if it was happening before? May I ask what your environment's `LOCALE` (or it might be stored as `LC_ALL`) and `LANG` are set to? And, by any chance, are you using Python2.6 or Jython? Or perhaps, did you do `gnupg.encrypt(None)` (sorry, I just have to ask)?

As far as which parts of the code to try poking at, `gnupg._util._make_binary_stream()`, `gnupg._meta.GnuPGBase._handle_io()`, and anything which uses `gnupg._meta.GnuPGBase._encoding` are probably equally likely culprits.

**Comment by marcwebbie** [comment]
Hello @isislovecruft 

I've been poking around `_meta` however I've made some changes to my lib and as you've suspected I was in some situations sending `None` to `encrypt`.

I will keep looking at my code and meta trying to reproduce this consistently to see if something shows up... for now you can close the issue.

Thanks for gnupg. It has been helping me in many projects. :smiley:

**Comment by isislovecruft** [comment]
@marcwebbie Great thanks! Feel free to reopen if you find anything.
