### ISSUE TITLE
Passphrase handling with and without GPG agent

### ISSUE THREAD

**Issue by torfsen** [isislovecruft/python-gnupg#114]
In my application, I need to frequently decrypt GPG-encrypted data using the user's own keys, which are usually protected by passphrases. In a traditional GPG session, the user would be prompted by GPG each time a passphrase is required and could use GPG agent to cache the passphrase. However, when using _python-gnupg_, GPG doesn't have access to a terminal, so direct user input to GPG is not possible:

```
> print gpg.encrypt(msg, default_key='some_fingerprint', encrypt=False).stderr
[GNUPG:] USERID_HINT XYZ Autogenerated Key (insecure!) <foo@bar>
[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0
gpg: Sorry, no terminal at all requested - can't get input
```

I've tried to use GPG agent with _python-gnupg_ via `gpg = gnupg.GPG(use_agent=True)`, but that just yields

```
> print gpg.encrypt(msg, default_key='some_fingerprint', encrypt=False).stderr
[GNUPG:] USERID_HINT XYZ Autogenerated Key (insecure!) <foo@bar>
[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0
gpg: gpg-agent is not available in this session
gpg: Sorry, no terminal at all requested - can't get input
```

Also, I cannot specify `passphrase=...` when calling `encrypt` if I initialized `GPG` using `use_agent=True`:

```
> print gpg.encrypt(msg, default_key='some_fingerprint', passphrase=str('secret'), encrypt=False).stderr
[GNUPG:] USERID_HINT XYZ Autogenerated Key (insecure!) <foo@bar>
[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0
gpg: gpg-agent is not available in this session
gpg: can't query passphrase in batch mode
[GNUPG:] MISSING_PASSPHRASE
[GNUPG:] BAD_PASSPHRASE XYZ
gpg: Invalid passphrase; please try again ...
[GNUPG:] USERID_HINT XYZ Autogenerated Key (insecure!) <foo@bar>
[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0
gpg: can't query passphrase in batch mode
[GNUPG:] MISSING_PASSPHRASE
[GNUPG:] BAD_PASSPHRASE XYZ
gpg: Invalid passphrase; please try again ...
[GNUPG:] USERID_HINT XYZ Autogenerated Key (insecure!) <foo@bar>
[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0
gpg: can't query passphrase in batch mode
[GNUPG:] MISSING_PASSPHRASE
[GNUPG:] BAD_PASSPHRASE XYZ
gpg: no default secret key: bad passphrase
gpg: signing failed: bad passphrase
```

Passing a passphrase works fine if `GPG` is initalized without `use_agent=True`. All these things also work fine when I use GPG via its command-line interface from a shell.

I'd rather not implement my own passphrase-cache. The ideal solution for me would be that _python-gnupg_ tells GPG to use GPG agent, which in turn asks the user for a passphrase (via STDOUT/STDIN). Alternatively, I'm fine with checking `result.stderr` for `NEED_PASSPHRASE`, query the passphrase from the user and providing it to _python-gnupg_ if that works in combination with GPG agent (i.e. I only have to do it once).

**Comment by eliasp** [comment]
When using an agent, you need the environment variable `GPG_AGENT_INFO` or GnuPG >= 2.1 which uses a static socket (`~/.gnupg/S.gpg-agent`) and auto-starts the agent when needed.

So you'd have to make sure the agent is started before your application and is configured to never time out.
Then either export `GPG_AGENT_INFO` for your application's environment or run a recent enough GnuPG version.

**Comment by torfuspolymorphus** [comment]
@ellasp: That doesn't seem to work over here. I'm running GPG 1.4.6, so I tried [starting the agent manually](https://www.gnupg.org/%28en%29/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html) via `gpg-connect-agent /bye`. This does set `GPG_AGENT_INFO`, but I still get the same errors as before:

```
> os.environ['GPG_AGENT_INFO']
'/tmp/gpg-SfWz93/S.gpg-agent:2411:1'
> gpg = gnupg.GPG(use_agent=True)
> gpg.encrypt(msg, default_key=fp, encrypt=False).stderr
u"[GNUPG:] USERID_HINT XYZ\n[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0\ngpg: gpg-agent is not available in this session\ngpg: Sorry, no terminal at all requested - can't get input\n"
> gpg = gnupg.GPG()  # without use_agent=True
> gpg.encrypt(msg, default_key=fp, encrypt=False).stderr
u"[GNUPG:] USERID_HINT XYZ\n[GNUPG:] NEED_PASSPHRASE XYZ XYZ 1 0\ngpg: Sorry, no terminal at all requested - can't get input\n"
```

**Comment by eliasp** [comment]
Please give GnuPG >= 2.1 a try - I'd say this is most likely to work then.

**Comment by torfuspolymorphus** [comment]
@eliasp: Unfortunately I'm currently stuck on 1.4.6. However, since it does work with native GPG (i.e. in the shell without going through pyghon-gnupg) I do think that there should be a way to get it working through python-gnupg, too.

**Comment by eliasp** [comment]
@isislovecruft Any ideas what to do/try here?

**Comment by isislovecruft** [comment]
@eliasp Hmm, this one is likely going to be tricky, and also the agent behaviour varies wildly between versions.

@torfuspolymorphus Did your agent already have the passphrase to the key loaded into it before you attempted to use it? The logs above show that the agent appears to be trying to request your passphrase (usually done through pinentry, which requires access to a terminal).

**Comment by torfuspolymorphus** [comment]
@isislovecruft: No, the agent didn't have the passphrase, yet. I don't think that should be necessary, though. As I wrote above I'd be OK with checking the error message for NEED_PASSPHRASE and providing it "manually" if that is necessary. However the passphrase should then be stored in the agent, something that doesn't seem to work over here. In an ideal world there would even be a way for me to tell the agent which terminal to use so that it can ask for the passphrase on its own.

**Comment by bechtoldt** [comment]
I had the same problem because I messed my gpg env up with various gpg versions/keyrings. After creating a new key, encrypting and decrypting with the same gpg2 binary everything starts working. :)

```
$ gpg2 --version
gpg (GnuPG) 2.1.6
libgcrypt 1.6.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
$ python --version
Python 3.4.3
```

```
$ pip freeze  | grep gnupg
gnupg==2.0.2
```

**Comment by amenonsen** [comment]
Shouldn't python-gnupg pass through GPG_TTY in the environment when it executes gpg? (use_agent=True doesn't work for me).

**Comment by amenonsen** [comment]
If I change the ``subprocess.Popen`` call in _meta.py to include the values of GPG_TTY and DISPLAY from the environment (if present), then pinentry works fine for me. @isislovecruft Is there any chance to get a 2.0.3 release with the above change? I'll submit a PR if you like.

**Comment by isislovecruft** [comment]
@torfsen Could you please retry with the new environment variable support (added in #131 and #115) and see if that works for you?
