### ISSUE TITLE
Symlinked binaries.

### ISSUE THREAD

**Issue by mattmb** [isislovecruft/python-gnupg#123]
Do we really have to disallow symlinked binaries. Is the concern that some program could be put in between that logs keys/data? The reason I ask is that: if you install gpg with brew on OSX, then brew uses symlinks to link the chosen version into your path so this blows up. Secondly we don't seem to make the symlink check on gpg2?

https://github.com/isislovecruft/python-gnupg/blob/2beac24161b07e40642d93f5d85faeb9740f78db/gnupg/_util.py#L420-L425

**Comment by mattmb** [comment]
cc @filipposc5 @krissaxton

**Comment by Tethik** [comment]
This also caused issue on my linux installation where gpg was symlinked to gpg2. Leading to a silent fail when trying to do anything.

**Comment by kerstin** [comment]
I'm interested in this as well, but I'm not sure if issues are being read. (The repo is still regularly being committed to but there are quite a number of issues also from 2015 which have never commented on, hmm.)

**Comment by isislovecruft** [comment]
Fixed in #69.

**Comment by ashb** [comment]
I don't think this issue is resolved - I'm still having trouble with default install of `gpg2` from brew and v2.3.1 of this module. What is the reason for disallowing symlinks?

(This requirement that gnupg be an absolute binary in the path is not documented anywhere that I could find either.)
