### ISSUE TITLE
multiple recipients encryption 

### ISSUE THREAD

**Issue by azafred** [isislovecruft/python-gnupg#124]
Hello, I can't seem to get gnupg to encrypt for multiple signatures at the same time.
I tried different approaches, depending on which doc / bug tracker I read, but I have not been able to find a suitable solution yet.
I have tried using a list of public keys fingerprint, and just a comma separated string, even multiple strings at the end of the encrypt function, but so far nothing as worked, and I am just presented with u"gpg: Sorry, no terminal at all requested - can't get input\n"

For background, here is what I am trying to accomplish:

``` python
>>> import gnupg
>>> from pprint import pprint
>>> gpg=gnupg.GPG(homedir='/home/fred/.gnupg')
>>> keys=gpg.list_keys()
>>> fprints=[]
>>> for key in keys:
...     if key['type'] == 'pub':
...         #print(str(key['fingerprint']))
...         fprints.append(str(key['fingerprint']))
... 
>>> stream=open('./README', 'r+')
>>> status=gpg.encrypt(stream, fprints, output='blah.gpg', always_trust=True)
>>> status.ok
False
>>> status.stderr
u"gpg: Sorry, no terminal at all requested - can't get input\n"
>>> 
>>> fprints=['EA0F2AE608C2302BE995F8EF55271EFDFAB9E213','741A9F6B4494A751DD7A46C59B5379E7DE0EBC0C']
>>> stream=open('./README', 'r+')
>>> status=gpg.encrypt(stream, fprints, output='blah.gpg', always_trust=True)
>>> status.stderr
u"gpg: Sorry, no terminal at all requested - can't get input\n"
>>> status.ok
False
```

Any help as to how to accomplish that would be greatly appreciated!

Cheers!

**Comment by amenonsen** [comment]
The documentation doesn't make this at all clear (and perhaps what you're trying once worked: I've found various similar examples in old code), but if you want to pass in a list of recipients like ``['AABBCCDD','EEFF9900']``, you have to call ``gpg.encrypt(plaintext, *recipients, …)``.

**Comment by isislovecruft** [comment]
I though [this](https://github.com/isislovecruft/python-gnupg/blob/master/gnupg/gnupg.py#L901) was pretty clear:

```
    def encrypt(self, data, *recipients, **kwargs):
        """Encrypt the message contained in ``data`` to ``recipients``.
        :param str data: The file or bytestream to encrypt.
        :param str recipients: The recipients to encrypt to. Recipients must
            be specified keyID/fingerprint. Care should be taken in Python2.x
            to make sure that the given fingerprint is in fact a string and
            not a unicode object.
```
But I've gone an added a note on how to encrypt to multiple recipients (basically just an explanation of how `*args` works in Python).
