### ISSUE TITLE
How to sign a file with exist key

### ISSUE THREAD

**Issue by zhangtianye** [isislovecruft/python-gnupg#127]
I want to sign a file,with a exist key stored in /home/z/mykey/.gnupg,
How can I use it to sign a file in python-gnupg?
When I use gpg.sign_file(stream),
I got a error: 'GPG' object has no attribute 'sign_file'

**Comment by stefan2904** [comment]
you could try ```sign```
https://python-gnupg.readthedocs.io/en/latest/gnupg.html#gnupg.GPG.sign
or ```_sign_file``` (internal API)
https://python-gnupg.readthedocs.io/en/latest/gnupg.html#gnupg._meta.GPGBase._sign_file

**Comment by isislovecruft** [comment]
Thanks for answering that @stefan2904!

@zhangtianye I hope that answered your question, feel free to reopen if otherwise.
