### ISSUE TITLE
Search and Send functionalities don't exist.

### ISSUE THREAD

**Issue by GeorgeGkas-zz** [isislovecruft/python-gnupg#130]
I installed the gnupg through `pip` in ubuntu and when I tried to search or send keys I get the following errors:

```
Traceback (most recent call last):
  File "gnugpg.py", line 6, in <module>
    gpg.search_keys('vinay_sajip@hotmail.com', 'keyserver.ubuntu.com')
AttributeError: 'GPG' object has no attribute 'search_keys'
```

```
Traceback (most recent call last):
  File "gnugpg.py", line 6, in <module>
    gpg.send_keys('keyserver.ubuntu.com', '6E4D5A2B')
AttributeError: 'GPG' object has no attribute 'send_keys'
```

Those are just the examples, but the errors are the same.

**Comment by tyroneyeh** [comment]
Same problem, solved to do:
rm -rf /usr/lib/python3.4/site-packages/gnupg

**Comment by isislovecruft** [comment]
@GeorgeGkas-zz You're using a different library, also named python-gnupg, created by Vinay Sajip. This library does not support search/send on purpose.

**Comment by NicoHood** [comment]
@isislovecruft why doesnt it support it on purpose? I need this function and the only way to work around this is to use the recv function.
