### ISSUE TITLE
[Question] Using master key for all the work?

### ISSUE THREAD

**Issue by GeorgeGkas-zz** [isislovecruft/python-gnupg#132]
I found out that the default master key created with `gnupg` have all the roles (S)igning, (E)ncryption, (A)uthentication and (C)ertification. 

My question is this:
Can I set the main role of the master key only to certificate and signining and set the encryption and authentication jobs to my sub-key?

**Comment by isislovecruft** [comment]
Please read the documentation for [the `gen_key()`](https://pythonhosted.org/gnupg/gnupg.html#gnupg.GPG.gen_key) and [`gen_key_input()`](https://pythonhosted.org/gnupg/gnupg.html#gnupg.GPG.gen_key_input) functions.
