### ISSUE TITLE
Ordered Dict requirement for python 2.6 is specified with hash but fails

### ISSUE THREAD

**Issue by antevens** [isislovecruft/python-gnupg#140]
Searching for ordereddict==1.1#a0ed854ee442051b249bfad0f638bbec
Reading https://pypi.python.org/simple/ordereddict/
No local packages or download links found for ordereddict==1.1#a0ed854ee442051b249bfad0f638bbec
error: Could not find suitable distribution for Requirement.parse('ordereddict==1.1#a0ed854ee442051b249bfad0f638bbec')

Removing the hash from the dependency specification fixes the issue.

Platform is Centos 6.7 x86_64 current with Python 2.6.6, and behind a Squid proxy for both HTTP and HTTPS.

**Comment by isislovecruft** [comment]
Yikes! The hash should match. Because it doesn't, I'm guessing something suspicious is happening at your Squid proxy (which is a nasty piece of software, by the way, which has historically been used for both censorship and malware delivery).

**Comment by antevens** [comment]
I think you are missing the point, the upstream package has does not match the hash you specified ...
