### ISSUE TITLE
Package broken(?)

### ISSUE THREAD

**Issue by ror6ax** [isislovecruft/python-gnupg#148]
What is the status of the project here? 
`Encrypt_file` is in reality `encrypt`.
`recepients=None` gives me `TypeError: _encrypt() got multiple values for keyword argument 'recipients'`

That's pretty basic stuff not working. Is there stable fork?

**Comment by isislovecruft** [comment]
You're using a different python-gnupg.

**Comment by ankostis** [comment]
Maybe choose a different name for the project?
