### ISSUE TITLE
Export with gpg 2.1.11 raises exception because of wrong parser class

### ISSUE THREAD

**Issue by jantman** [isislovecruft/python-gnupg#151]
```
>>> k = gpg.export_keys(['ee5c1f5b412d53b3'])
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jantman/tmp/foo/lib/python2.7/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/home/jantman/tmp/foo/lib/python2.7/site-packages/gnupg/_parsers.py", line 895, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'EXPORTED'
```

But the returned value is correct.

The problem appears to be in [gnupg.py L442](https://github.com/isislovecruft/python-gnupg/blob/2.0.2/gnupg/gnupg.py#L442):

``` python
        p = self._open_subprocess(args)
        ## gpg --export produces no status-fd output; stdout will be empty in
        ## case of failure
        #stdout, stderr = p.communicate()
        result = self._result_map['delete'](self)  # any result will do
```

However, DeleteResult [raises ValueError](https://github.com/isislovecruft/python-gnupg/blob/2.0.2/gnupg/_parsers.py#L886) if the status message is anything other than "DELETE_PROBLEM". It seems that, at least for newer gpg versions, Export should either have its own result parser, or use one that ignores the status.

On a related note, could the documentation say which gpg versions this works with? Or perhaps issue some sort of message when `GPG()` is instantiated with an unsupported binary?

**Comment by isislovecruft** [comment]
Fixed in python-gnupg version 2.2.0.
