### ISSUE TITLE
Incorrect shebang for __init__.py

### ISSUE THREAD

**Issue by NicoHood** [isislovecruft/python-gnupg#184]
python2-gnupg E: Dependency python detected and not included (programs ['python'] needed in scripts ['usr/lib/python2.7/site-packages/gnupg/__init__.py'])

When installing python-gnupg with setuptools the shebang needs to be changed for each python version.

**Comment by sigmavirus24** [comment]
I'm actually surprised there's a shebang even there. That should probably not even exist.

**Comment by NicoHood** [comment]
Also setuptools produce `/usr/bin/versioneer.py` which is available for python2 and 3. It seems that this is only required at packaging time and should not exist in the final package. But I am not sure about this. Maybe this needs to be fixed as well.

**Comment by isislovecruft** [comment]
Fixed in the next version (2.3.2). Thanks for the report!
