### ISSUE TITLE
-no-tty is enforced even if not in gpg.conf or...

### ISSUE THREAD

**Issue by krysopath** [isislovecruft/python-gnupg#189]
i just cloned commit adc6f0e9b5ce6d476fa09b3add9746867e7bff2c to check out if this got changed.

I am working with keys that might or not might be signed already, but I till use them for encryption purposes programmatically.  I have encryption failures everytime, when I want to use an unsigned/untrusted key, because the gpg binary wants to have it's yes/NO, which I could figure out from the returned gnupg._parsers.Crypt.stderr, which reads that `gpg: Sorry, no terminal at all requested - can't get input` and internet wide and long told me I'd have to disable the `no-tty` in my gpg.conf, which wasn't there to begin with. So I am left wondering. Is the use of no `--no-tty` avoided intentionally? I spent quite some time to understand why sometimes my encryption failed.

in gnupg._meta line 545:
```
cmd = [self.binary,
               '--no-options --no-emit-version --no-tty --status-fd 2']
```
I tried passing  `gnupg.GPG(options="") `or `gnupg.GPG(options={})` to convince the magic to do my bidding.  I was thinking by setting options explicitly, I could perhaps override gnupg's default command, but it didn't worked out. Is their a way to disable this option somehow, when i initialise the GPG()?

If not, I suppose adding some boolean arg to the `GPG.__init__` and the `GPGBase.__init__()` might be easy enough, because i need this flag to vanish. I don't find any solutions to my specific case online and nothing in the docs about disabling it.

How to solve this? For now I am implementing changes in a local branch. What is your opinion on this, dear sirs?

**Comment by shollingsworth** [comment]
Hi there, did you ever figure this out?

**Comment by shollingsworth** [comment]
Figured out what it was. I passed an array instead of a argument series..
i.e. `self.recipients" = [<key1>,<key2>,<key3>,...]` , calling like this:
`e = self.gpg.encrypt(plaintext,self.recipients)` throws the "no terminal error"
switching to: 
`e = self.gpg.encrypt(plaintext,*self.recipients)`  works!
