### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Nando-bog** [isislovecruft/python-gnupg#49]
I am getting a UnicodeDecodeError when decrypting a text that was encrypted using the library. However, the text is decypted properly despite the error.

Details:
OS: Mac OS Mavericks 10.9.2
Python: 2.7.6
gnupg: 1.2.5

Sample error from my Terminal:

> from gnupg import GPG
> g=GPG(homedir='MY GPG HOME DIR')
> c=g.encrypt('hola', 'KEY ID')
> p=g.decrypt(str(c), passphrase='MYPASSWORD')
> Exception in thread Thread-8:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/Library/Python/2.7/site-packages/gnupg/_meta.py", line 532, in _read_response
>     line = stream.readline()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 530, in readline
>     data = self.read(readsize, firstline=True)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 477, in read
>     newchars, decodedbytes = self.decode(data, self.errors)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 0: invalid continuation byte
> print(p)
> hola

As the last line shows, decryption worked, but it still threw the error. 

Thanks!

**Comment by pwfff** [comment]
This solution needs to be rethought. Changing this global callback is affecting other code, most notably the DataStax Cassandra driver. The exception in the following code is never raised, so what is already valid UTF-8 has its characters replaced with garbage: https://github.com/datastax/python-driver/blob/master/cassandra/cqltypes.py#L675

**Comment by sawall** [comment]
This solution definitely needs to be rethought. It breaks MIME encodings of attachments, e.g., the base64 representation of an image will be munged here:
`import gnupg
gpg = gnupg.GPG('/path/to/gpg')

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage

def send_my_email():
    msg = MIMEMultipart()
    msg['Subject'] = 'subject'
    msg['From'] = 'XXXX@gmail.com'
    msg['To'] = 'YYYY@gmail.com'
    with open('/tmp/image.jpg', mode='rb') as image_file:
        image = MIMEImage(image_file.read())
    msg.attach(image)
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login('XXXX@gmail.com', 'password')
    s.send_message(msg)
    s.quit()`

**Comment by sawall** [comment]
Note that a workaround for this glitch is to define `gpgon` and `gpgoff` functions and use them around any gpg calls.

    import codecs
    default_strict_func = codecs.lookup_error('strict')
    import gnupg
    gpg = gnupg.GPG(app.config['GPG_LOCATION'])
    gpg_strict_func = codecs.lookup_error('strict')
    def gpgon(): codecs.register_error('strict', gpg_strict_func)
    def gpgoff(): codecs.register_error('strict', default_strict_func)
    gpgoff() # disable monkey patch by default

**Comment by e3rd** [comment]
Thanks for posting this workaround!! I've expanded it so that you may use GPGSafe class instead of gnupg.GPG without having to manage anything.

https://gist.github.com/e3rd/45aed2e93ac20843b6790b6b642da396
