### ISSUE TITLE
Signing is failing if when passphrase='' (empty string)

### ISSUE THREAD

**Issue by majek** [isislovecruft/python-gnupg#82]
When running:

g = gnupg.GPG(...)
x = g.sign('abc\ndef\n, passphrase='')
print x.data

The signed thing will be only "def\n", "abc" will be skipped in the signature. When passphrase=None it's fine.

**Comment by isislovecruft** [comment]
Fixed in my `fix/82-passphrase-empty-str` branch and merged.
