### ISSUE TITLE
PY3: signing of StringIO fails

### ISSUE THREAD

**Issue by ttanner** [isislovecruft/python-gnupg#88]
the following test fails with Python 3.4.
It hangs forever and if you abort the process you get:

Traceback (most recent call last):
  File ".../3.4/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File ".../3.4/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File ".../python-gnupg/gnupg/_util.py", line 162, in _copy_data
    outstream.write(data)
TypeError: 'str' does not support the buffer interface

    def test_signature_stringio(self):
        """Test that signing a message file works."""
        key = self.generate_key("Leonard Adleman", "rsa.com")
        message_file = os.path.join(_files, 'cypherpunk_manifesto')
        msg = io.StringIO(open(message_file,'rt').read())
        sig = self.gpg.sign(msg, default_key=key.fingerprint,
                            passphrase='leonardadleman')
        self.assertTrue(sig, "I thought I typed my password correctly...")

**Comment by isislovecruft** [comment]
This is merged and it'll be fixed in python-gnupg>=2.0.1.

@ttanner Thanks for reporting the issue!
