### ISSUE TITLE
MISSING_PASSPHRASE not handled

### ISSUE THREAD

**Issue by ttanner** [isislovecruft/python-gnupg#91]
when the passphrase is missing, gnupg returns MISSING_PASSPHRASE.
this message should be handled like BAD_PASSPHRASE

 File ".../gnupg-1.4.0-py2.7.egg/gnupg/_parsers.py", line 950, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'MISSING_PASSPHRASE'

**Comment by isislovecruft** [comment]
Okay, this is fixed in my `fix/91-missing-passphrase` branch.
