### ISSUE TITLE
Don't pass --use-agent or --no-use-agent to gpg2

### ISSUE THREAD

**Issue by garrettr** [isislovecruft/python-gnupg#96]
From `man gpg2`:

```
--use-agent

--no-use-agent
       This is dummy option. gpg2 always requires the agent.
```

The `gnupg.GPG` constructor calls `_make_args`, which defaults to setting `--no-use-agent` if `use_agent` is not specified as a keyword argument to the constructor. When python-gnupg uses gpg2, this causes gpg2 to print a warning message *every time it is called*:

```
vagrant@development:~$ gpg2 --no-use-agent
gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
gpg: Go ahead and type your message ...
```

This message cannot be suppressed even by changing the `--debug-level` to `none`. When used in an automated fashion (such as in SecureDrop), this creates a lot of log noise.

Since neither argument has an effect with gpg2, they should not be set when python-gnupg is used with gpg2.

**Comment by isislovecruft** [comment]
Fixed in my `fix/96-no-use-agent` branch, which merged a commit from @ttanner from #46. This branch has been merged into `develop` for the 2.0.1 release.
